version: "2"

run:
  go: "1.21"
  timeout: 10m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Optional linters
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - gosec
    - misspell
    - noctx
    - nolintlint
    - revive
    - whitespace

  settings:
    revive:
      severity: error
    staticcheck:
      go: "1.21"
